# GitHub Actions docs
# https://help.github.com/en/articles/about-github-actions
# https://help.github.com/en/articles/workflow-syntax-for-github-actions
    
name: Test and Release
on: [push]

jobs:
  test-and-release:
    name: Run tests and release
    runs-on: ubuntu-18.04
    steps:
    - name: Setup Node.js
      uses: actions/setup-node@v1
      with:
        node-version: 14.13.1
    - name: Install dependencies
      run: npm install
    - name: Lint
      run: npm run lint
    - name: Build
      run: npm run build-all
    - name: Test
      run: npm run test
    - name: Release
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
      run: npm run semantic-release
